base:
  show_state: true
  show_icon: true
  double_tap_action:
    haptic: success
  hold_action:
    action: block
  color_type: icon
  aspect_ratio: 1/1
  card_size: 1
  state_display: >
    [[[
      if (entity.state == 'unavailable')
        return 'N/A'
      if (entity.state == 'off')
        return 'Av'
      if (entity.state == 'on')
        return 'På'
    ]]]
  extra_styles: |
    #secondary ha-icon {
      height: auto !important;
      width: 65% !important;
    }
    @media (max-width:  800px) {
      #name {
        font-size: 10px
      }
      #card {
        padding: 10px
      }
    }
    @media (min-width: 1025px) {
      #name {
        font-size: 14px
      }
      #card {
        padding: 14px
      }
    }
  styles:
    card:
      - display: flex
      - flex: 1
      - color: >
          [[[
            return (entity.state == 'unavailable')
              ? "var(--disabled-text-color)"
              : 'var(--primary-text-color)';
          ]]]
      
      - background-color: >
          [[[
            return (entity.state == 'unavailable')
              ? 'var(--paper-card-disabled-background-color)'
              : 'var(--paper-card-background-color)';
          ]]]
      #- border: 'var(--paper-card-background-color)'
      - border-style: solid
      - border-width: 1px
      - border-color: 'var(--divider-color)'
      - border-radius: 12px
      - font-family: "Arimo, system-ui"
      - transition: 0.3s ease-out
      - padding: 8px
    grid:
      - grid-template-areas: |
          "i  secondary"
          "n  n"
          "s  s"
      - grid-template-columns: repeat(2, 1fr)
      - grid-template-rows: auto repeat(2, min-content)
      - gap: 1.3%
      - align-items: start
      - will-change: transform
    img_cell:
      - align-self: start
      - text-align: start
      - justify-content: start
    icon:
      - align-self: start
      - text-align: start
      - width: 65%
      - height: auto
    name:
      - justify-self: start
      - text-wrap: wrap
      - word-break: break-all
      - text-align: left
      
    state:
      - justify-self: start
      - font-size: 12px
      - color: >
          [[[
            return (entity.state == 'unavailable')
              ? 'var(--disabled-text-color)'
              : 'var(--disabled-text-color)';
          ]]]
      - justify-self: start
      - line-height: 125%
      
      
    custom_fields:
      secondary:      
      - justify-self: end
      - text-align: end
      - width: 100%
      - height: 100%
      - color: >
          [[[
            return (entity.state == 'unavailable')
              ? "var(--secondary-text-color)"
              : 'rgba(255, 255, 255, 0.80)';
          ]]]


base2:
  show_state: true
  show_icon: true
  double_tap_action:
    haptic: success
  hold_action:
    action: block
  aspect_ratio: 1/1
  color_type: icon
  extra_styles: |
    #secondary ha-icon {
      height: 65% !important;
      width: 65% !important;
      margin: 0 0 0 auto;
    }
    #img-cell ha-state-icon {
      height: 65% !important;
      width: auto !important;
      #margin: 0 0 0 auto;
      #left: 0px;
      #top: 0px;
    }
  styles:
    grid:
      - grid-template-areas: |
          "i  secondary"
          "n  n"
          "s  s"
      - grid-template-columns: 1fr
      - grid-template-rows: 1fr min-content min-content
    name:
      - justify-self: start
      - line-height: 125%
      - font-weight: bold
      #- font-size: 80%
      #- height: 50%
      #- display: flex
      - text-wrap: wrap
      - word-break: break-all
      - text-align: left
      - font-size: 14px
      - color: var(--primary-text-color)
    state:
      - font-size: 12px
      - color: var(--secondary-text-color)
      - justify-self: start
      - line-height: 125%
      
    card:
      - display: flex
      - flex: 1
      - background-color: 'rgb(33,38,40)'
      - border: '1px solid rgb(80,80,80)'
      - border-radius: 12% 
      - font-family: "Arimo, system-ui"
      - padding: 10px
      - color: >
          [[[
            if (entity.state == 'unavailable')
              return "#808080"
          ]]]  
    img_cell:
      - justify-content: flex-start
    #icon:
    #  - left: 0px
    #  - top: 0px
    #  - width: 50%
    #  - margin: 0 0 0 auto;
    custom_fields:
      secondary:
        - display: flex
        - grid-area: secondary
        - height: 100%
        - width: 100%
        - max-width: 100%
        - max-height: 100%
        - overflow: hidden
        - align-items: start
        

  state_display: >
    [[[
      if (entity.state == 'unavailable')
        return 'N/A'
      if (entity.state == 'off')
        return 'Av'
    ]]]
